spring:
  application:
    name: hhplus-server
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/hhplus
#    username:
#    password:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        ddl-auto: create
#        format_sql: true
#        show_sql: true
#        naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy