spring:
  application:
    name: hhplus-server
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/hhplus_concert
#    username:
#    password:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create-drop
        format_sql: true
        show_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy