-- Insert into user table
INSERT INTO "user" (name, point) VALUES ('Alice', 21000);
INSERT INTO "user" (name, point) VALUES ('Bob', 10800);
INSERT INTO "user" (name, point) VALUES ('Charlie', 150000);
INSERT INTO "user" (name, point) VALUES ('Diana', 5000);
INSERT INTO "user" (name, point) VALUES ('Eve', 17000);

-- Insert info quque table
INSERT INTO queue (user_id, token, status, activated_at, created_at, updated_at) VALUES (1, '4d51a296-d7da-4b0f-bc59-32ecd64a042a', 'ACTIVE', now(), now(), now());
INSERT INTO queue (user_id, token, status, activated_at, created_at, updated_at) VALUES (2, '1df3dbdc-2dsf-3fdg-bd32-3dmsd32dfdk1', 'ACTIVE', now(), now(), now());

-- Insert into place table
INSERT INTO place (name) VALUES ('Stadium A');
INSERT INTO place (name) VALUES ('Concert Hall B');

-- Insert into seat table
-- Seats for Stadium A
INSERT INTO seat (place_id, seat_no) VALUES (1, 1);
INSERT INTO seat (place_id, seat_no) VALUES (1, 2);
INSERT INTO seat (place_id, seat_no) VALUES (1, 3);
INSERT INTO seat (place_id, seat_no) VALUES (1, 4);
INSERT INTO seat (place_id, seat_no) VALUES (1, 5);
INSERT INTO seat (place_id, seat_no) VALUES (1, 6);
INSERT INTO seat (place_id, seat_no) VALUES (1, 7);
INSERT INTO seat (place_id, seat_no) VALUES (1, 8);
INSERT INTO seat (place_id, seat_no) VALUES (1, 9);
INSERT INTO seat (place_id, seat_no) VALUES (1, 10);
INSERT INTO seat (place_id, seat_no) VALUES (1, 11);
INSERT INTO seat (place_id, seat_no) VALUES (1, 12);
INSERT INTO seat (place_id, seat_no) VALUES (1, 13);
INSERT INTO seat (place_id, seat_no) VALUES (1, 14);
INSERT INTO seat (place_id, seat_no) VALUES (1, 15);
INSERT INTO seat (place_id, seat_no) VALUES (1, 16);
INSERT INTO seat (place_id, seat_no) VALUES (1, 17);
INSERT INTO seat (place_id, seat_no) VALUES (1, 18);
INSERT INTO seat (place_id, seat_no) VALUES (1, 19);
INSERT INTO seat (place_id, seat_no) VALUES (1, 20);
INSERT INTO seat (place_id, seat_no) VALUES (1, 21);
INSERT INTO seat (place_id, seat_no) VALUES (1, 22);
INSERT INTO seat (place_id, seat_no) VALUES (1, 23);
INSERT INTO seat (place_id, seat_no) VALUES (1, 24);
INSERT INTO seat (place_id, seat_no) VALUES (1, 25);
INSERT INTO seat (place_id, seat_no) VALUES (1, 26);
INSERT INTO seat (place_id, seat_no) VALUES (1, 27);
INSERT INTO seat (place_id, seat_no) VALUES (1, 28);
INSERT INTO seat (place_id, seat_no) VALUES (1, 29);
INSERT INTO seat (place_id, seat_no) VALUES (1, 30);
INSERT INTO seat (place_id, seat_no) VALUES (1, 31);
INSERT INTO seat (place_id, seat_no) VALUES (1, 32);
INSERT INTO seat (place_id, seat_no) VALUES (1, 33);
INSERT INTO seat (place_id, seat_no) VALUES (1, 34);
INSERT INTO seat (place_id, seat_no) VALUES (1, 35);
INSERT INTO seat (place_id, seat_no) VALUES (1, 36);
INSERT INTO seat (place_id, seat_no) VALUES (1, 37);
INSERT INTO seat (place_id, seat_no) VALUES (1, 38);
INSERT INTO seat (place_id, seat_no) VALUES (1, 39);
INSERT INTO seat (place_id, seat_no) VALUES (1, 40);
INSERT INTO seat (place_id, seat_no) VALUES (1, 41);
INSERT INTO seat (place_id, seat_no) VALUES (1, 42);
INSERT INTO seat (place_id, seat_no) VALUES (1, 43);
INSERT INTO seat (place_id, seat_no) VALUES (1, 44);
INSERT INTO seat (place_id, seat_no) VALUES (1, 45);
INSERT INTO seat (place_id, seat_no) VALUES (1, 46);
INSERT INTO seat (place_id, seat_no) VALUES (1, 47);
INSERT INTO seat (place_id, seat_no) VALUES (1, 48);
INSERT INTO seat (place_id, seat_no) VALUES (1, 49);
INSERT INTO seat (place_id, seat_no) VALUES (1, 50);

-- Seats for Concert Hall B
INSERT INTO seat (place_id, seat_no) VALUES (2, 1);
INSERT INTO seat (place_id, seat_no) VALUES (2, 2);
INSERT INTO seat (place_id, seat_no) VALUES (2, 3);
INSERT INTO seat (place_id, seat_no) VALUES (2, 4);
INSERT INTO seat (place_id, seat_no) VALUES (2, 5);
INSERT INTO seat (place_id, seat_no) VALUES (2, 6);
INSERT INTO seat (place_id, seat_no) VALUES (2, 7);
INSERT INTO seat (place_id, seat_no) VALUES (2, 8);
INSERT INTO seat (place_id, seat_no) VALUES (2, 9);
INSERT INTO seat (place_id, seat_no) VALUES (2, 10);
INSERT INTO seat (place_id, seat_no) VALUES (2, 11);
INSERT INTO seat (place_id, seat_no) VALUES (2, 12);
INSERT INTO seat (place_id, seat_no) VALUES (2, 13);
INSERT INTO seat (place_id, seat_no) VALUES (2, 14);
INSERT INTO seat (place_id, seat_no) VALUES (2, 15);
INSERT INTO seat (place_id, seat_no) VALUES (2, 16);
INSERT INTO seat (place_id, seat_no) VALUES (2, 17);
INSERT INTO seat (place_id, seat_no) VALUES (2, 18);
INSERT INTO seat (place_id, seat_no) VALUES (2, 19);
INSERT INTO seat (place_id, seat_no) VALUES (2, 20);
INSERT INTO seat (place_id, seat_no) VALUES (2, 21);
INSERT INTO seat (place_id, seat_no) VALUES (2, 22);
INSERT INTO seat (place_id, seat_no) VALUES (2, 23);
INSERT INTO seat (place_id, seat_no) VALUES (2, 24);
INSERT INTO seat (place_id, seat_no) VALUES (2, 25);
INSERT INTO seat (place_id, seat_no) VALUES (2, 26);
INSERT INTO seat (place_id, seat_no) VALUES (2, 27);
INSERT INTO seat (place_id, seat_no) VALUES (2, 28);
INSERT INTO seat (place_id, seat_no) VALUES (2, 29);
INSERT INTO seat (place_id, seat_no) VALUES (2, 30);
INSERT INTO seat (place_id, seat_no) VALUES (2, 31);
INSERT INTO seat (place_id, seat_no) VALUES (2, 32);
INSERT INTO seat (place_id, seat_no) VALUES (2, 33);
INSERT INTO seat (place_id, seat_no) VALUES (2, 34);
INSERT INTO seat (place_id, seat_no) VALUES (2, 35);
INSERT INTO seat (place_id, seat_no) VALUES (2, 36);
INSERT INTO seat (place_id, seat_no) VALUES (2, 37);
INSERT INTO seat (place_id, seat_no) VALUES (2, 38);
INSERT INTO seat (place_id, seat_no) VALUES (2, 39);
INSERT INTO seat (place_id, seat_no) VALUES (2, 40);
INSERT INTO seat (place_id, seat_no) VALUES (2, 41);
INSERT INTO seat (place_id, seat_no) VALUES (2, 42);
INSERT INTO seat (place_id, seat_no) VALUES (2, 43);
INSERT INTO seat (place_id, seat_no) VALUES (2, 44);
INSERT INTO seat (place_id, seat_no) VALUES (2, 45);
INSERT INTO seat (place_id, seat_no) VALUES (2, 46);
INSERT INTO seat (place_id, seat_no) VALUES (2, 47);
INSERT INTO seat (place_id, seat_no) VALUES (2, 48);
INSERT INTO seat (place_id, seat_no) VALUES (2, 49);
INSERT INTO seat (place_id, seat_no) VALUES (2, 50);

-- Insert into concert table
INSERT INTO concert (title, casting) VALUES ('Concert 1', 'Artist A');
INSERT INTO concert (title, casting) VALUES ('Concert 2', 'Artist B');
INSERT INTO concert (title, casting) VALUES ('Concert 3', 'Artist C');

-- Insert into concert_schedule table
-- Schedules for Concert 1
INSERT INTO concert_schedule (concert_id, place_id, concert_datetime) VALUES (1, 1, '2024-08-01 19:00:00');
INSERT INTO concert_schedule (concert_id, place_id, concert_datetime) VALUES (1, 2, '2024-08-02 20:00:00');

-- Schedules for Concert 2
INSERT INTO concert_schedule (concert_id, place_id, concert_datetime) VALUES (2, 1, '2024-08-03 19:00:00');
INSERT INTO concert_schedule (concert_id, place_id, concert_datetime) VALUES (2, 2, '2024-08-04 20:00:00');

-- Schedules for Concert 3
INSERT INTO concert_schedule (concert_id, place_id, concert_datetime) VALUES (3, 1, '2024-08-05 19:00:00');
INSERT INTO concert_schedule (concert_id, place_id, concert_datetime) VALUES (3, 2, '2024-08-06 20:00:00');

-- Insert into concert_seat table
-- Seats for first schedule of Concert 1
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 1, 'OCCUPIED', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 2, 'OCCUPIED', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 3, 'OCCUPIED', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 4, 'OCCUPIED', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 5, 'OCCUPIED', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 6, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 7, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 8, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 9, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 10, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 11, 'OCCUPIED', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 12, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 13, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 14, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 15, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 16, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 17, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 18, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 19, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 20, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 21, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 22, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 23, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 24, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 25, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 26, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 27, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 28, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 29, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 30, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 31, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 32, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 33, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 34, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 35, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 36, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 37, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 38, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 39, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 40, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 41, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 42, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 43, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 44, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 45, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 46, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 47, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 48, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 49, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (1, 50, 'AVAILABLE', 10000, 1);

-- Seats for second schedule of Concert 1
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 51, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 52, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 53, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 54, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 55, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 56, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 57, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 58, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 59, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 60, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 61, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 62, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 63, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 64, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 65, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 66, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 67, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 68, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 69, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 70, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 71, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 72, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 73, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 74, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 75, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 76, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 77, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 78, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 79, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 80, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 81, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 82, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 83, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 84, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 85, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 86, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 87, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 88, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 89, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 90, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 91, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 92, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 93, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 94, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 95, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 96, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 97, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 98, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 99, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (2, 100, 'AVAILABLE', 15000, 1);


-- Seats for first schedule of Concert 2
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 1, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 2, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 3, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 4, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 5, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 6, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 7, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 8, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 9, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 10, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 11, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 12, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 13, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 14, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 15, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 16, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 17, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 18, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 19, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 20, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 21, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 22, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 23, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 24, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 25, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 26, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 27, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 28, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 29, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 30, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 31, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 32, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 33, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 34, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 35, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 36, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 37, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 38, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 39, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 40, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 41, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 42, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 43, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 44, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 45, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 46, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 47, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 48, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 49, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (3, 50, 'AVAILABLE', 10000, 1);

-- Seats for second schedule of Concert 2
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 51, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 52, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 53, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 54, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 55, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 56, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 57, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 58, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 59, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 60, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 61, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 62, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 63, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 64, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 65, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 66, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 67, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 68, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 69, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 70, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 71, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 72, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 73, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 74, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 75, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 76, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 77, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 78, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 79, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 80, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 81, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 82, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 83, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 84, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 85, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 86, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 87, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 88, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 89, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 90, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 91, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 92, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 93, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 94, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 95, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 96, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 97, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 98, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 99, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (4, 100, 'AVAILABLE', 15000, 1);

-- Seats for first schedule of Concert 3
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 1, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 2, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 3, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 4, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 5, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 6, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 7, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 8, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 9, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 10, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 11, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 12, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 13, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 14, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 15, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 16, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 17, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 18, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 19, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 20, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 21, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 22, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 23, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 24, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 25, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 26, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 27, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 28, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 29, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 30, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 31, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 32, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 33, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 34, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 35, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 36, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 37, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 38, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 39, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 40, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 41, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 42, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 43, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 44, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 45, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 46, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 47, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 48, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 49, 'AVAILABLE', 10000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (5, 50, 'AVAILABLE', 10000, 1);

-- Seats for second schedule of Concert 3
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 51, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 52, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 53, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 54, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 55, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 56, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 57, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 58, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 59, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 60, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 61, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 62, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 63, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 64, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 65, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 66, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 67, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 68, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 69, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 70, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 71, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 72, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 73, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 74, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 75, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 76, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 77, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 78, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 79, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 80, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 81, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 82, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 83, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 84, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 85, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 86, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 87, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 88, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 89, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 90, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 91, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 92, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 93, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 94, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 95, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 96, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 97, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 98, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 99, 'AVAILABLE', 15000, 1);
INSERT INTO concert_seat (concert_schedule_id, seat_id, status, price, version) VALUES (6, 100, 'AVAILABLE', 15000, 1);


INSERT INTO reservation (user_id, concert_schedule_id, place_id, concert_title, concert_casting, concert_datetime, place_name, total_price, status, created_at, created_by, updated_by, updated_at)
VALUES (1, 1, 1, 'Awesome Concert', 'Famous Band', '2024-08-01 19:00:00', 'Main Hall', 20000, 'RESERVED', '2024-07-18 10:00:00', '1', '1', '2024-07-18 10:00:00');

INSERT INTO reservation_ticket (reservation_id, concert_seat_id, seat_id, seat_no, price) VALUES (1, 4, 4, 4, 10000);

INSERT INTO reservation_ticket (reservation_id, concert_seat_id, seat_id, seat_no, price) VALUES (1, 5, 5, 5, 10000);

INSERT INTO reservation (user_id, concert_schedule_id, place_id, concert_title, concert_casting, concert_datetime, place_name, total_price, status, created_at, created_by, updated_by, updated_at)
VALUES (2, 1, 1, 'Awesome Concert', 'Famous Band', '2024-08-01 19:00:00', 'Main Hall', 10000, 'RESERVED', now(), '2', '2', now());

INSERT INTO reservation_ticket (reservation_id, concert_seat_id, seat_id, seat_no, price) VALUES (2, 11, 11, 11, 10000);